// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SibSample.Infrastructure.Database;

namespace SibSample.Infrastructure.Database.Design.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20201029065934_UpInitalSchemaTables")]
    partial class UpInitalSchemaTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SibSample.Domain.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("ISPB")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("SibSample.Domain.Bank", b =>
                {
                    b.OwnsOne("SibSample.Domain.Documents.Document", "Document", b1 =>
                        {
                            b1.Property<Guid>("BankId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasColumnName("Document")
                                .HasColumnType("text");

                            b1.HasKey("BankId");

                            b1.HasIndex("Value");

                            b1.ToTable("Banks");

                            b1.WithOwner()
                                .HasForeignKey("BankId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
